name: soav_
channels:
    - conda-forge
    - pytorch
dependencies:
    - python==3.6.9
    - pip 
    - numpy
    - matplotlib
    - pillow
    - eventlet
    - flask-socketio
    - tqdm
    - pytorch
    - torchvision
    - cudatoolkit
    - pip:
        - python-socketio==4.2.1
        - opencv-python
        - tensorboard_logger
